### ISSUE TITLE
All history, keyboard shortcut to search

### ISSUE THREAD

**Issue by bs** [Vincent-P/firefox-better-history#12]
Hey, thanks for your work! Two questions:

1. Is there a reason to not include the ability to search all history?

2. What about a keyboard shortcut to quickly open and have search focused?

**Comment by architchandra** [comment]
Yes, a shortcut to open the history would be amazing!

**Comment by capellavacancies** [comment]
is there a way to make ctrl+h open this extension instead of firefox history ?
thanks

**Comment by architchandra** [comment]
Thanks @Vincent-P!

Just FYI for the others, the keyboard shortcut can be checked/edited from the extension settings. On Macs, the shortcut seems to be `Option + Cmd + H`.
