### ISSUE TITLE
Can I trigger this with ctrl+h ?

### ISSUE THREAD

**Issue by capellavacancies** [Vincent-P/firefox-better-history#21]
Thanks

**Comment by bricakeld** [comment]
what if you can open the extension using another keyboard shortcut that doesn't conflict with existing Firefox keyboard shortcuts instead?

**Comment by capellavacancies** [comment]
thanks for your reply, I don't find any way to trigger this extension with a keyboard shortcut though

**Comment by rcherny** [comment]
I was looking for a way to open this with a keyboard shortcut as well. It doesn't appear to have a preference for this, from what I could see. It'd be great if it did.
