### ISSUE TITLE
Application in Full Screen

### ISSUE THREAD

**Issue by aGnamZer0** [Vincent-P/firefox-better-history#30]
Hello,

I don't dare to call this an issue as I use this add-on for years and I love it. It's simple, practical, and complete.

However, I do have a request. Would it be possible to have the possibility to open the UI on a new tab if we need it? I like how it is as a pop-up right now, but in some cases it's unpractical. In particular, I think about when I make a search. If I do one for a website I use often – like YouTube as there is constant background music on my computer – the number of pages displayed makes up most of the space used by the pop-up. In the case of YouTube, I have 289 pages, and I simply can't see the search results.

I have added an image of what it looks like for me when I search YouTube.

![Improved History](https://user-images.githubusercontent.com/39864051/134086815-b28bc6b0-8da3-4fb3-9a56-ca3403c55424.png)

And unfortunately, I have similar cases on other searches – though not quite as bad.

Having a button in the pop-up where we can choose to open it in a new window would be a great boon. No need to change the working of the add-on however, it works wonderfully.

To finish, I want to thank you for creating this awesome application for us. The history manager of Firefox is simply horrendous and I definitely would have stopped using this browser if not for you. So thanks!

I hope you'll be able to do something about my request.

Best regards,

-aGnamZer0

**Comment by bricakeld** [comment]
Hi, not sure if you got the right extension's repository?

**Comment by Vincent-P** [comment]
This repository is about the Firefox extension not the Chrome one sorry.
