### ISSUE TITLE
browser.extension.getURL deprecated

### ISSUE THREAD

**Issue by thoellrich** [Vincent-P/firefox-better-history#33]
I'm seeing the following error in FF 95.0.2 on Windows: 
![image](https://user-images.githubusercontent.com/5420081/147879032-4033f3bc-3a25-418d-b6d1-e7f50561dcc8.png)

PR https://github.com/Vincent-P/firefox-better-history/pull/32 should fix this.

**Comment by Vincent-P** [comment]
Hi,
Thanks for your PR, the extension will be updated soon.

**Comment by thoellrich** [comment]
Thanks for merging it so quickly and also thanks for the extension! Happy New Year!
