### ISSUE TITLE
Feature request: Add ability to change first day of the week

### ISSUE THREAD

**Issue by Jackymancs4** [Vincent-P/firefox-better-history#4]
Hello @Vincent-P 
I've been using your extension since I saw it on Firefox's Subreddit, and it's quite an improvement. It let you feel the Vivaldi spirit ;)

So, I prepared a batch of feedback that hopefully will help you improve the extension. I should be able to fill all of them by tomorrow. Still, thanks for making this!

---

Where I live the week start with Monday, not Sunday.

Can you add an option to change it in the week view?
As an alternative, you can try using the [Intl APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) to infer the preferred first day of the week. I have not investigated if it's actually possible, but I would guess it is.

**Comment by Vincent-P** [comment]
Hi thanks for your issues!
Internationalization is definitely on the todo list, I will do it whenever I have time.
