### ISSUE TITLE
Dark mode link text is difficult to read

### ISSUE THREAD

**Issue by Jackymancs4** [Vincent-P/firefox-better-history#5]
In dark mode the link buttons use the color [#0060df](https://www.colorhexa.com/0060df) on a [#404043](https://www.colorhexa.com/404043) background (in the css it's `--grey-10-a10`).

According to https://webaim.org/resources/contrastchecker/?fcolor=0060DF&bcolor=404043 it has an extremely bad contrast, and in fact it is difficult for me to properly read the text without increasing the screen luminosity.

Same thing with the loading spinner (same colors).

I'd suggest to replace the blue color with [#4fbcff](https://www.colorhexa.com/4fbcff), used by Reddit in its dark mode.

**Comment by Vincent-P** [comment]
I will use a brighter blue in the next update, thanks for suggesting a color but Better History follows the [Photon Design guidelines](https://design.firefox.com/photon/) so I think I will use `--blue-40`.
