### ISSUE TITLE
Feedback: remove globes icons from items

### ISSUE THREAD

**Issue by Jackymancs4** [Vincent-P/firefox-better-history#6]
While I can understand the needs for a little iconography, the globes on the right on the titles serves no real purpose, and most likely never will as History APIs does not provides a way to retrieve sites icons.

Also, while scrolling they cause me a slight [Grid illusion - Wikipedia](https://en.wikipedia.org/wiki/Grid_illusion) which is quite annoying.

My suggestion is remove them.

**Comment by Vincent-P** [comment]
It's a placeholder that will be replaced by the website's favicon once we figure out a reliable way to retrieve it.
