### ISSUE TITLE
Suggestion: Use the Firefox Quantum tab spinner for loading

### ISSUE THREAD

**Issue by Jackymancs4** [Vincent-P/firefox-better-history#8]
Since you cited the Photon Design System, I think it would really look good (almost native).

As a reference for possible implementation this issue: https://github.com/piroor/treestyletab/issues/ 1384

**Comment by ladevieq** [comment]
We will implement it as soon as possible

**Comment by Vincent-P** [comment]
I think the current spinner is pretty good already.
I don't think there are any cpu usage problems as it uses CSS animations.
